---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: attendee-service-source-temp

run:
  path: attendee-service-source/ci/tasks/test-temp.sh
