---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: moviefun

run:
  path: apps-movie-fun-code/ci/tasks/run-unit-tests
